version: '3'
networks:
  integration-test:
    driver: bridge

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - integration-test
    volumes:
      - $PWD:/go/src/server
    ports:
      - 8080:8080

  client_test:
    build: 
      context: .
      dockerfile: Dockerfile.test
    networks:
      - integration-test
    volumes:
      - $PWD:/go/src/client
    depends_on:
      - server
    environment:
      - server_host=server
